name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: sosohungry
          outputs: |
            output/github-snake-dark.svg
            output/github-snake-light.svg